Seq2 checkmate
weirichs/eatTools pull request #15
Opened 2024-01-19 10:52 UTC by grewered

I started adding checks to the functions. I added checkmate-package to the DESCRIPTION and implemented the checks for this function. 
Should I add new tests in test_seq2.R as well?

2024-01-23 15:55 UTC, weirichs commented
> I started adding checks to the functions. I added checkmate-package to the DESCRIPTION and implemented the checks for this function. Should I add new tests in test_seq2.R as well?

Yes, new tests would be beneficial, the old ones fail. Thanks!

2024-01-23 15:56 UTC, weirichs requested changes

2024-01-23 15:56 UTC, weirichs commented on DESCRIPTION
Thanks, looks good to me!

2024-01-23 15:56 UTC, weirichs commented on R/seq2.R
thanks again, looks good ...

2024-01-23 15:56 UTC, weirichs commented on R/seq2.R
I do not see whether there is a (conceptual) difference between `checkmate::assert_number(from)` and `checkmate::assert_numeric(from, len = 1)` ... I think both work well.

2024-01-23 15:56 UTC, weirichs commented on tests/testthat/test_seq2.R
The tests failed because I receive a different error message than expected. 
```
Fehler: `seq2("d", "t")` threw an error with unexpected message.
Expected match: "Must be of type 'number', not 'character'"
Actual message: "Assertion on 'from' failed: Must be of type 'numeric', not 'character'."
```
I suspect that the error messages returned by `checkmate::assert_number()` and `checkmate::assert_numeric()` differ slightly in wording, although they are functionally equivalent.

2024-01-25 12:43 UTC, grewered commented on tests/testthat/test_seq2.R
yes, but I think the assert_numeric ones are a bit more informative, so I think I'll go with them for now. corrected them now.

2024-01-25 12:53 UTC, grewered reviewed
it seems to work now. shall I add more tests (for NAs or NULL arguments, for instance) or is this enough and shall I move to the next function?

2024-01-25 18:17 UTC, weirichs commented on tests/testthat/test_seq2.R
Thanks, I'm fine with that. I'll try to merge the seq2_checkmate branch into master branch and approve all changes so we can move to the next function.

2024-01-25 18:17 UTC, merged