add tests for halveString
weirichs/eatTools pull request #2
Opened 2023-02-22 16:36 UTC by weirichs

2023-02-22 16:46 UTC, beckerbenj requested changes
I like the tests, just some minor formalities 👍

2023-02-22 16:47 UTC, beckerbenj commented on tests/testthat/test_halveString.R
> +context("halveString")
see also [context](https://testthat.r-lib.org/reference/context.html)

2023-02-23 22:50 UTC, weirichs commented on tests/testthat/test_halveString.R
> +context("halveString")
Will be done (second option)

2023-02-23 22:51 UTC, weirichs commented on tests/testthat/test_halveString.R
> +d1  <- halveString(str, pattern = "__", colnames= c("a", "b"))
Will be done, sir!

2023-02-23 23:02 UTC, merged